<?php
$url = Chat\Framework\Bootstrap::BaseUrl();
?>

       <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Online Chat By Alex</title>

        <link rel="stylesheet" type="text/css" href="<?php echo $url ?>/skin/js/jScrollPane/jScrollPane.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo $url ?>/skin/css/page.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo $url ?>/skin/css/chat.css" />

        <script>
            function getBaseUrl() {
                return "<?php echo $url; ?>";
            }
        </script>
    