<?php
$url = Chat\Framework\Bootstrap::BaseUrl();

$error = \Chat\Framework\Bootstrap::registry('error');
if ($error):
    ?>
    <div class="alert alert-danger">
        <strong><?php echo $error; ?></strong>
    </div>
<?php endif; ?>


<!-- Top content -->
<div class="top-content">

    <div class="inner-bg">
        <div class="container">

            <div class="row">
                <div class="col-sm-8 col-sm-offset-2 text">
                    <h1><strong>OnlineChat</strong> Login &amp; Register</h1>
                    <div class="description">
                        <p>
                            To use <strong>Online Chat</strong> and participate in discussions, please register or login. 
                        </p>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-5">

                    <div class="form-box">
                        <div class="form-top">
                            <div class="form-top-left">
                                <h3>Login to chat</h3>
                                <p>Enter username and password to log on:</p>
                            </div>
                            <div class="form-top-right">
                                <i class="fa fa-lock"></i>
                            </div>
                        </div>
                        <div class="form-bottom">
                            <form role="form" action="<?php echo $url . '/index/login' ?>" method="post" class="login-form">
                                <div class="form-group">
                                    <label class="sr-only" for="form-username">Username</label>
                                    <input type="text" name="name" placeholder="Username..." class="form-username form-control" id="form-username">
                                </div>
                                <div class="form-group">
                                    <label class="sr-only" for="form-password">Password</label>
                                    <input type="password" name="password" placeholder="Password..." class="form-password form-control" id="form-password">
                                </div>
                                <button type="submit" class="btn">Sign in!</button>
                            </form>
                        </div>
                    </div>

                </div>

                <div class="col-sm-1 middle-border"></div>
                <div class="col-sm-1"></div>

                <div class="col-sm-5">

                    <div class="form-box">
                        <div class="form-top">
                            <div class="form-top-left">
                                <h3>Sign up now</h3>
                                <p>Fill in the form below to get instant access:</p>
                            </div>
                            <div class="form-top-right">
                                <i class="fa fa-pencil"></i>
                            </div>
                        </div>
                        <div class="form-bottom">
                            <form role="form" action="<?php echo $url . '/index/register' ?>" method="post" class="registration-form">
                                <div class="form-group">
                                    <label class="sr-only" for="form-name">Username</label>
                                    <input type="text" name="name" placeholder="First name..." class="form-first-name form-control required" id="first-name">
                                </div>
                                <div class="form-group">
                                    <label class="sr-only" for="register-password">Password</label>
                                    <input type="password" name="password" placeholder="Password..." class="form-password form-control required" id="register-password">
                                </div>
                                <div class="form-group">
                                    <label class="sr-only" for="register-email">Email</label>
                                    <input type="text" name="email" placeholder="Email..." class="form-email form-control required" id="register-email">
                                </div>
                                <div class="form-group">
                                   <!-- <label class="sr-only" for="homepage">Home Page</label>-->
                                    <input type="text" name="homepage" placeholder="Home Page..." class="form-control" id="homepage">
                                </div>
                                <button type="submit" class="btn">Sign me up!</button>
                            </form>
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>

</div>

<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">

            <div class="col-sm-8 col-sm-offset-2">
                <div class="footer-border"></div>
                <p>Made by Alex Gudenko <a href="http://github.com/locoss/onlinechat" target="_blank"><strong>GITHUB</strong></a> 
                    <i class="fa fa-smile-o"></i></p>
            </div>

        </div>
    </div>
</footer>

<!-- Javascript -->
<script src="<?php echo $url ?>/skin/assets/js/jquery-1.11.1.min.js"></script>
<script src="<?php echo $url ?>/skin/assets/bootstrap/js/bootstrap.min.js"></script>
<script src="<?php echo $url ?>/skin/assets/js/jquery.backstretch.min.js"></script>
<script src="<?php echo $url ?>/skin/assets/js/scripts.js"></script>

<!--[if lt IE 10]>
    <script src="assets/js/placeholder.js"></script>
<![endif]-->