<?php 
$url = Chat\Framework\Bootstrap::BaseUrl();
?>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Making an Web Chat</title>

        <link rel="stylesheet" type="text/css" href="<?php echo $url ?>/skin/js/jScrollPane/jScrollPane.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo $url ?>/skin/css/page.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo $url ?>/skin/css/chat.css" />
	<script>
	function getBaseUrl(){
		return "<?php echo $url; ?>";
	}
	</script>
    </head>

    <body>

        <div id="chatContainer">

            <div id="chatTopBar" class="rounded"></div>
            <div id="chatLineHolder">
            </div>

            <div id="chatUsers" class="rounded"> 
            </div>
            <div id="chatBottomBar" class="rounded">
                <div class="tip"></div>

                <form id="loginForm" method="post" action="">
                    <input id="name" name="name" class="rounded" maxlength="16" />
                    <input id="email" name="email" class="rounded" />
                    <input type="submit" class="blueButton" value="Login" />
                </form>

                <form id="submitForm" method="post" action="">
                    <input id="chatText" name="chatText" class="rounded" maxlength="255" />
                    <input type="submit" class="blueButton" value="Submit" />
                </form>

            </div>

        </div>

        <div id="footer">
            <div class="tri"></div>
            <h1></h1> 
        </div>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
        <script src="<?php echo $url ?>/skin/js/jScrollPane/jquery.mousewheel.js"></script>
        <script src="<?php echo $url ?>/skin/js/jScrollPane/jScrollPane.min.js"></script>
        <script src="<?php echo $url ?>/skin/js/script.js"></script>
    </body>
</html>
